// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/article/article-item.vue')['default'];
    Asd: typeof import('./src/components/asd/index.vue')['default'];
    Asdz: typeof import('./src/components/asdz/index.vue')['default'];
    ElTag: typeof import('element-plus/es')['ElTag'];
    Index: typeof import('./src/components/common/label/Index.vue')['default'];
    Label: typeof import('./src/components/common/label/index.vue')['default'];
    LabelIndex: typeof import('./src/components/common/label/label-index.vue')['default'];
    LabelNormal: typeof import('./src/components/common/label/label-normal.vue')['default'];
    LabelTodo: typeof import('./src/components/common/label/label-todo.vue')['default'];
    LayoutHeader: typeof import('./src/components/layout/layout-header.vue')['default'];
    Normal: typeof import('./src/components/common/label/normal.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Zxc: typeof import('./src/components/zxc/index.vue')['default'];
  }
}
